FROM astral/uv:python3.14-bookworm-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    gcc \
    g++ \
    cmake \
    ninja-build \
    curl \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

RUN uv pip install --no-cache --system --break-system-packages -r requirements.txt

COPY *.py .
ENV PYTHONDONTWRITEBYTECODE=1
CMD ["python", "game_master.py"]
