FROM astral/uv:python3.14-bookworm-slim

WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN uv venv
RUN uv pip install --no-cache-dir -r requirements.txt

# Copy application
COPY . .

# Run bot
CMD ["python", "bot.py"]