"""
Language constants for Telegram Bot
All user-facing strings should be defined here with Russian and English versions
"""

LANGUAGE_RU = "ru"
LANGUAGE_EN = "en"

ONBOARDING = {
    LANGUAGE_RU: {
        "welcome": None,  # Generated by LLM in game_master.py
        "welcome_back": "С возвращением, {role}!\n\n{role_description}\nХарактеристики: {traits}\n\nИспользуйте /today для просмотра текущего дня игры.",
        "question_prefix": "Ситуация {id}:\n\n{text}",
        "onboarding_complete": "🎉 Добро пожаловать на борт!\n\nВаша роль: **{role}**\n\n{role_description}\n\n**Вид:** {species}\n**Пол:** {gender}\n\n**Характеристики:**\n- {traits}",
        "game_already_started": "🚀 Игра уже началась, добро пожаловать на борт!",
        "game_waiting": "⏳ Игра скоро начнётся, ждём остальных игроков.",
        "new_player_joined": "👋 Новый член экипажа присоединился к нам!\n\n**{player_name}** — **{role}**\n\n{role_description}",
        "select_game": "🎮 **Выберите игру, к которой хотите присоединиться, или начните новую:**",
        "new_game": "🆕 Начать новую игру",
        "invite_title": "🎯 **Пригласите друзей!**",
        "invite_message": "Поделитесь этой ссылкой с друзьями, чтобы они присоединились к вашей игре:\n{invite_url}",
        "invite_button": "🔗 Пригласить друга",
        "already_in_onboarding": "Вы уже проходите онбординг. Пожалуйста, ответьте на текущий вопрос.",
        "game_starting_broadcast": "🚀 Игра начинается! {player_name} присоединился, и команда в полном составе!\n\n**{player_name}** — **{role}**\n\n{role_description}",
    },
    LANGUAGE_EN: {
        "welcome": None,  # Generated by LLM in game_master.py
        "welcome_back": "Welcome back, {role}!\n\n{role_description}\nTraits: {traits}\n\nUse /today to view the current game day.",
        "question_prefix": "Situation {id}:\n\n{text}",
        "onboarding_complete": "🎉 Welcome aboard!\n\nYour role: **{role}**\n\n{role_description}\n\n**Species:** {species}\n**Gender:** {gender}\n\n**Traits:**\n- {traits}",
        "game_already_started": "🚀 The game has already started! The crew is assembled. Use /today for the current turn and /bridge to view the mission.",
        "game_waiting": "⏳ The game will start soon, we're waiting for more players.",
        "new_player_joined": "👋 A new crew member has joined us!\n\n**{player_name}** — **{role}**\n\n{role_description}",
        "select_game": "🎮 **Select a game to join or start a new one:**",
        "new_game": "🆕 Start New Game",
        "invite_title": "🎯 **Invite friends!**",
        "invite_message": "Share this link with friends so they can join your game:\n{invite_url}",
        "invite_button": "🔗 Share Invite Link",
        "already_in_onboarding": "You are already in onboarding. Please answer the current question.",
        "game_starting_broadcast": "🚀 The game is starting! {player_name} has joined, and the crew is assembled!\n\n**{player_name}** — **{role}**\n\n{role_description}",
    },
}

# Commands help
HELP = {
    LANGUAGE_RU: {
        "title": None,  # Game title fetched dynamically from API
        "regular_commands": "Команды:\n/start - Начать или продолжить игру\n/profile - Показать ваш профиль\n/today - Текущий ход игры\n/bridge - Картинка рубки и миссия\n/help - Эта справка",
        "gm_commands": "Команды Game Master:\n/gm_start_game <id> - Запустить игру\n/gm_continue_game <id> - Сгенерировать следующий ход\n/gm_regenerate_turn <id> - Перегенерировать текущий ход\n/gm_restart_game <id> - Перезапустить игру с 1 хода\n/gm_kick <id> <роль> [причина] - Изгнать игрока\n/gm_list_games - Список всех игр",
        "how_to_play": "Как играть:\n1. Каждый ход генерируется новый сюжет\n2. Вы выбираете действия из предложенных вариантов\n3. Ваши решения влияют на развитие истории\n4. Вы можете общаться с Game Master в любое время\n\nНапишите сообщение для общения с Game Master.",
    },
    LANGUAGE_EN: {
        "title": None,  # Game title fetched dynamically from API
        "regular_commands": "Commands:\n/start - Start or continue the game\n/profile - Show your profile\n/today - Current game turn\n/bridge - Bridge image and mission\n/help - This help",
        "gm_commands": "Game Master Commands:\n/gm_start_game <id> - Start a game\n/gm_continue_game <id> - Generate the next turn\n/gm_regenerate_turn <id> - Regenerate the current turn\n/gm_restart_game <id> - Restart the game from turn 1\n/gm_kick <id> <role> [reason] - Kick a player\n/gm_list_games - List all games",
        "how_to_play": "How to play:\n1. A new story is generated every turn\n2. You choose actions from the suggested options\n3. Your decisions affect the story development\n4. You can communicate with the Game Master at any time\n\nWrite a message to communicate with the Game Master.",
    },
}

# Profile messages
PROFILE = {
    LANGUAGE_RU: {
        "title": "👤 **Ваш профиль**",
        "role": "**Роль:** {role}",
        "species": "**Вид:** {species}",
        "gender": "**Пол:** {gender}",
        "description": "{role_description}",
        "traits": "**Характеристики:**\n- {traits}",
        "visualization": "**Визуализация:** {avatar}",
        "no_profile": "У вас ещё нет профиля. Пройдите онбординг с помощью /start",
    },
    LANGUAGE_EN: {
        "title": "👤 **Your Profile**",
        "role": "**Role:** {role}",
        "species": "**Species:** {species}",
        "gender": "**Gender:** {gender}",
        "description": "{role_description}",
        "traits": "**Traits:**\n- {traits}",
        "visualization": "**Visualization:** {avatar}",
        "no_profile": "You don't have a profile yet. Complete onboarding with /start",
    },
}

# Current day messages
CURRENT_DAY = {
    LANGUAGE_RU: {
        "title": "🎯 **Ход {day}**",
        "story": "*Общая вводная:*\n{story}",
        "crew_dialogues": "*NPC диалоги:*",
        "actions": "*Ваши варианты действий:*\n{actions}",
        "select_action": "Выберите действие ниже:",
        "briefing_header": "{briefing}",
        "error": "Не удалось получить информацию о текущем ходе: {error}",
    },
    LANGUAGE_EN: {
        "title": "🎯 **Turn {day}**",
        "story": "*Global scenario:*\n{story}",
        "crew_dialogues": "*NPC dialogues:*",
        "actions": "*Your action choices:*\n{actions}",
        "select_action": "Select an action below:",
        "briefing_header": "{briefing}",
        "error": "Could not get information about the current turn: {error}",
    },
}

# Action selection
ACTIONS = {
    LANGUAGE_RU: {
        "recorded": "Ваш выбор записан!\n\nGame Master обработает ваше решение и обновит сюжет.\n\nВы можете продолжить общение с Game Master или подождать следующего дня.",
        "error": "Произошла ошибка при записи выбора: {error}",
    },
    LANGUAGE_EN: {
        "recorded": "Your choice has been recorded!\n\nThe Game Master will process your decision and update the plot.\n\nYou can continue communicating with the Game Master or wait for the next day.",
        "error": "An error occurred while recording the choice: {error}",
    },
}

# Message handling
MESSAGES = {
    LANGUAGE_RU: {
        "voice_received": "Спасибо за голосовое сообщение!\nGame Master получил ваше сообщение.\nПримечание: голосовые сообщения пока не поддерживают преобразование в текст.",
        "text_received": "Game Master получил ваше сообщение.\nОтвет будет сгенерирован в ближайшее время.",
        "error": "Произошла ошибка: {error}",
        "game_master_response": "Game Master получил ваше сообщение.",
    },
    LANGUAGE_EN: {
        "voice_received": "Thank you for the voice message!\nThe Game Master has received your message.\nNote: Voice messages do not support text-to-speech conversion yet.",
        "text_received": "The Game Master has received your message.\nThe response will be generated shortly.",
        "error": "An error occurred: {error}",
        "game_master_response": "Game Master received your message.",
    },
}

# Error messages
ERRORS = {
    LANGUAGE_RU: {
        "invalid_format": "Неверный формат ответа",
        "session_not_found": "Сессия не найдена. Пожалуйста, начните заново с /start",
        "onboarding_error": "Произошла ошибка при запуске: {error}",
    },
    LANGUAGE_EN: {
        "invalid_format": "Invalid answer format",
        "session_not_found": "Session not found. Please start again with /start",
        "onboarding_error": "An error occurred during startup: {error}",
    },
}

# Loading / splash screen messages
IMAGES = {
    LANGUAGE_RU: {
        "loading_caption": "🚀 Инициализация системы... Загрузка звёздного компьютера.",
        "processing_caption": "✨ Ваши ответы обрабатываются. Личное дело шифрутеся звёздной пылью",
    },
    LANGUAGE_EN: {
        "loading_caption": "🚀 System initializing... Starship computer booting up.",
        "processing_caption": "✨ Your answer processing. Stellar cartography mapping your destiny",
    },
}

# Bridge image messages
BRIDGE = {
    LANGUAGE_RU: {
        "title": "🚀 **Мостик корабля**",
        "error": "Картинка рубки пока не сгенерирована. Дождитесь начала миссии.",
        "mission_header": "**Миссия:** {name}",
        "mission_desc": "{description}",
    },
    LANGUAGE_EN: {
        "title": "🚀 **Bridge**",
        "error": "Bridge image not yet generated. Wait for the mission to start.",
        "mission_header": "**Mission:** {name}",
        "mission_desc": "{description}",
    },
}

# Spectator (dead player) messages
SPECTATOR = {
    LANGUAGE_RU: {
        "player_dead": "💀 **Вы погибли при исполнении!**\n\nВаш персонаж пал в бою. Вы остаётесь зрителем и можете наблюдать за развитием сюжета.\n\nЧтобы присоединиться к новой игре или вернуться в текущую в новой роли, нажмите /start",
        "still_watching": "👁 **Вы наблюдаете за развитием событий...**\n\nКак зритель, вы видите сюжет, но не можете влиять на него.\nНажмите /start чтобы присоединиться к новой игре или вернуться в новой роли.",
    },
    LANGUAGE_EN: {
        "player_dead": "💀 **You died in the line of duty!**\n\nYour character fell in battle. You remain a spectator and can watch the story unfold.\n\nTo join a new game or return to the current one in a new role, press /start",
        "still_watching": "👁 **You are watching the story unfold...**\n\nAs a spectator, you see the plot but cannot influence it.\nPress /start to join a new game or return in a new role.",
    },
}

# Menu labels
MENU = {
    LANGUAGE_RU: {
        "start": "/start",
        "profile": "/profile",
        "today": "/today",
        "help": "/help",
    },
    LANGUAGE_EN: {
        "start": "/start",
        "profile": "/profile",
        "today": "/today",
        "help": "/help",
    },
}

# Game Master command responses
GM_COMMANDS = {
    LANGUAGE_RU: {
        "unauthorized": "⛔ У вас нет прав на использование этой команды.",
        "start_game_usage": "❌ Использование: /gm_start_game <game_id>\n\nПример: /gm_start_game abc123",
        "starting_game": "🚀 Запуск игры `{game_id}`...",
        "continue_game_usage": "❌ Использование: /gm_continue_game <game_id>\n\nПример: /gm_continue_game abc123",
        "continuing_game": "🚀 Генерация следующего хода для игры `{game_id}`...",
        "game_continued": "✅ **Следующий ход сгенерирован!**\n\n🎯 Ход: {day_num}\n👤 Игроков: {players}\n🤖 NPC: {npcs}\n🎭 Участников: {total}",
        "continue_game_error": "❌ Ошибка генерации хода: {error}",
        "regenerate_turn_usage": "❌ Использование: /gm_regenerate_turn <game_id>\n\nПример: /gm_regenerate_turn abc123",
        "regenerating_turn": "🔄 Перегенерация текущего хода для игры `{game_id}`...",
        "turn_regenerated": "✅ **Текущий ход перегенерирован!**\n\n🎯 Ход: {day_num}\n👤 Игроков: {players}\n🤖 NPC: {npcs}",
        "regenerate_turn_error": "❌ Ошибка перегенерации хода: {error}",
        "restart_game_usage": "❌ Использование: /gm_restart_game <game_id>\n\nПример: /gm_restart_game abc123",
        "restarting_game": "🔄 Перезапуск игры `{game_id}`...",
        "game_restarted": "✅ **Игра перезапущена и запущена!**\n\n🎮 Игра: `{game_id}`\n🗑 Удалено ходов: {deleted_days}\n🗑 Удалено брифингов: {deleted_briefings}\n🗑 Удалено действий: {deleted_actions}\n🗑 Удалено сообщений: {deleted_messages}\n🗑 Удалена миссия: {deleted_mission}\n\n🎯 Ход: {day_num}\n👤 Игроков: {player_count}\n🤖 NPC создано: {npc_count}\n🚀 Миссия сгенерирована",
        "restart_game_error": "❌ Ошибка перезапуска игры: {error}",
        "game_started": "✅ **Игра `{game_id}` запущена!**\n\n🎯 Ход: {day_num}\n👤 Игроков: {player_count}\n🤖 NPC создано: {npc_count}\n🚀 Миссия сгенерирована\n🖼 Картинка рубки готова\n\nКоманда собрана, вводные разосланы!",
        "briefings_sent": "",
        "start_game_error": "❌ Ошибка запуска игры: {error}",
        "kick_usage": "❌ Использование: /gm_kick <game_id> <role_key> [причина]\n\nПример: /gm_kick abc123 chief_engineer Неактивен более 3 дней",
        "default_kick_reason": "Не указана",
        "kicking_player": "⏳ Изгнание игрока с ролью `{role_key}` из игры `{game_id}`...",
        "player_kicked": "✅ **Игрок изгнан!**\n\n🎮 Игра: `{game_id}`\n👤 Игрок: `{kicked_id}`\n🤖 Заменён NPC: {npc_name}\n📝 Причина: {reason}\n\nУведомление отправлено игроку.",
        "unknown_error": "Неизвестная ошибка",
        "no_api_response": "Нет ответа от API",
        "kick_error": "❌ Ошибка изгнания игрока: {error}",
        "no_games": "📋 **Список игр:**\n\nПока нет доступных игр.",
        "games_list_header": "📋 **Список игр:**",
        "games_list_entry": "{idx}. `{game_id}` — Игра: {title} ({player_count} игрока, {status_icon} {status})",
        "default_game_title": "Без названия",
        "list_games_error": "❌ Ошибка получения списка игр: {error}",
    },
    LANGUAGE_EN: {
        "unauthorized": "⛔ You don't have permission to use this command.",
        "start_game_usage": "❌ Usage: /gm_start_game <game_id>\n\nExample: /gm_start_game abc123",
        "starting_game": "🚀 Starting game `{game_id}`...",
        "continue_game_usage": "❌ Usage: /gm_continue_game <game_id>\n\nExample: /gm_continue_game abc123",
        "continuing_game": "🚀 Generating next turn for game `{game_id}`...",
        "game_continued": "✅ **Next turn generated!**\n\n🎯 Turn: {day_num}\n👤 Players: {players}\n🤖 NPCs: {npcs}\n🎭 Total: {total}",
        "continue_game_error": "❌ Error generating turn: {error}",
        "regenerate_turn_usage": "❌ Usage: /gm_regenerate_turn <game_id>\n\nExample: /gm_regenerate_turn abc123",
        "regenerating_turn": "🔄 Regenerating current turn for game `{game_id}`...",
        "turn_regenerated": "✅ **Current turn regenerated!**\n\n🎯 Turn: {day_num}\n👤 Players: {players}\n🤖 NPCs: {npcs}",
        "regenerate_turn_error": "❌ Error regenerating turn: {error}",
        "restart_game_usage": "❌ Usage: /gm_restart_game <game_id>\n\nExample: /gm_restart_game abc123",
        "restarting_game": "🔄 Restarting game `{game_id}`...",
        "game_restarted": "✅ **Game restarted and started!**\n\n🎮 Game: `{game_id}`\n🗑 Days deleted: {deleted_days}\n🗑 Briefings deleted: {deleted_briefings}\n🗑 Actions deleted: {deleted_actions}\n🗑 Messages deleted: {deleted_messages}\n🗑 Mission deleted: {deleted_mission}\n\n🎯 Turn: {day_num}\n👤 Players: {player_count}\n🤖 NPCs created: {npc_count}\n🚀 Mission generated",
        "restart_game_error": "❌ Error restarting game: {error}",
        "game_started": "✅ **Game `{game_id}` started!**\n\n🎯 Turn: {day_num}\n👤 Players: {player_count}\n🤖 NPCs created: {npc_count}\n🚀 Mission generated\n🖼 Bridge image ready\n\nCrew assembled, briefings sent!",
        "briefings_sent": "",
        "start_game_error": "❌ Error starting game: {error}",
        "kick_usage": "❌ Usage: /gm_kick <game_id> <role_key> [reason]\n\nExample: /gm_kick abc123 chief_engineer Inactive for more than 3 days",
        "default_kick_reason": "Not specified",
        "kicking_player": "⏳ Kicking player with role `{role_key}` from game `{game_id}`...",
        "player_kicked": "✅ **Player kicked!**\n\n🎮 Game: `{game_id}`\n👤 Player: `{kicked_id}`\n🤖 Replaced by NPC: {npc_name}\n📝 Reason: {reason}\n\nNotification sent to player.",
        "unknown_error": "Unknown error",
        "no_api_response": "No API response",
        "kick_error": "❌ Error kicking player: {error}",
        "no_games": "📋 **Game list:**\n\nNo games available yet.",
        "games_list_header": "📋 **Game list:**",
        "games_list_entry": "{idx}. `{game_id}` — {title} ({player_count} players, {status_icon} {status})",
        "default_game_title": "Untitled",
        "list_games_error": "❌ Error fetching game list: {error}",
    },
}


def get_onboarding(language: str = LANGUAGE_RU):
    """Get onboarding messages for a specific language"""
    return ONBOARDING.get(language, ONBOARDING[LANGUAGE_RU])


def get_help(language: str = LANGUAGE_RU):
    """Get help messages for a specific language"""
    return HELP.get(language, HELP[LANGUAGE_RU])


def get_profile(language: str = LANGUAGE_RU):
    """Get profile messages for a specific language"""
    return PROFILE.get(language, PROFILE[LANGUAGE_RU])


def get_current_day(language: str = LANGUAGE_RU):
    """Get current day messages for a specific language"""
    return CURRENT_DAY.get(language, CURRENT_DAY[LANGUAGE_RU])


def get_actions(language: str = LANGUAGE_RU):
    """Get action messages for a specific language"""
    return ACTIONS.get(language, ACTIONS[LANGUAGE_RU])


def get_messages(language: str = LANGUAGE_RU):
    """Get message handling strings for a specific language"""
    return MESSAGES.get(language, MESSAGES[LANGUAGE_RU])


def get_errors(language: str = LANGUAGE_RU):
    """Get error messages for a specific language"""
    return ERRORS.get(language, ERRORS[LANGUAGE_RU])


def get_menu(language: str = LANGUAGE_RU):
    """Get menu labels for a specific language"""
    return MENU.get(language, MENU[LANGUAGE_RU])


def get_images(language: str = LANGUAGE_RU):
    """Get loading/splash image messages for a specific language"""
    return IMAGES.get(language, IMAGES[LANGUAGE_RU])


def get_gm_commands(language: str = LANGUAGE_RU):
    """Get Game Master command response strings for a specific language"""
    return GM_COMMANDS.get(language, GM_COMMANDS[LANGUAGE_RU])


def get_bridge(language: str = LANGUAGE_RU):
    """Get bridge image messages for a specific language"""
    return BRIDGE.get(language, BRIDGE[LANGUAGE_RU])


def get_spectator(language: str = LANGUAGE_RU):
    """Get spectator/dead player messages for a specific language"""
    return SPECTATOR.get(language, SPECTATOR[LANGUAGE_RU])
