"""
Language constants for Telegram Bot
All user-facing strings should be defined here with Russian and English versions
"""

LANGUAGE_RU = "ru"
LANGUAGE_EN = "en"

LANGUAGE_FLAGS = {
    LANGUAGE_RU: "🇷🇺",
    LANGUAGE_EN: "🇬🇧",
}


HELLO = {
    LANGUAGE_RU: "Здравствуйте",
    LANGUAGE_EN: "Hello",
}


LANGUAGE_NAMES = {
    LANGUAGE_RU: {
        LANGUAGE_RU: "Русский",
        LANGUAGE_EN: "English",
    },
    LANGUAGE_EN: {
        LANGUAGE_RU: "Russian",
        LANGUAGE_EN: "English",
    },
}

ONBOARDING = {
    LANGUAGE_RU: {
        "welcome": None,  # Generated by LLM in game_server.py
        "welcome_back": "С возвращением, {role}!\n\n{role_description}\nХарактеристики: {traits}\n\nИспользуйте /turn для просмотра текущего хода игры.",
        "question_prefix": "Ситуация {id}:\n\n{text}",
        "onboarding_complete": "🎉 Добро пожаловать на борт!\n\nВаша роль: **{role}**\n\n{role_description}\n\n**Вид:** {species}\n**Пол:** {gender}\n\n**Характеристики:**\n- {traits}",
        "game_already_started": "🚀 Игра уже началась, добро пожаловать на борт!",
        "game_waiting": "⏳ Игра скоро начнётся, ждём остальных игроков.",
        "new_player_joined": "👋 Новый член экипажа присоединился к нам!\n\n**{player_name}** — **{role}**\n\n{role_description}",
        "select_game": "🎮 **Выберите игру, к которой хотите присоединиться, или начните новую:**",
        "selected_game": "Вы выбрали 🎮 {game_name}",
        "new_game": "🆕 Начать новую игру",
        "invite_title": "🎯 **Пригласите друзей!**",
        "invite_message": "Поделитесь этой ссылкой с друзьями, чтобы они присоединились к вашей игре:\n{invite_url}",
        "invite_button": "🔗 Пригласить друга",
        "share_text": "Присоединяйся к игре",
        "invite_mission_caption": "Приглашаю вас в игру «{game_title}»!\n\n🚀 **Миссия «{mission_name}»**\n\n{mission_description}\n\n{invite_url}",
        "invite_no_mission_caption": "Приглашаю вас в игру «{game_title}»!\n\n{invite_url}",
        "invite_forward": "👆 Перешли сообщение выше другу!\n\nИли отправь ему эту ссылку:\n{invite_url}",
        "already_in_onboarding": "Вы уже проходите онбординг. Пожалуйста, ответьте на текущий вопрос.",
        "onboarding_complete_restored": "🎉 Ваш онбординг уже завершён! Создаю ваш профиль...",
        "stale_onboarding_session": "😕 Ваша сессия онбординга устарела. Нажмите кнопку ниже, чтобы очистить её и начать заново.",
        "clear_session_button": "🔄 Очистить и начать заново",
        "game_starting_broadcast": "🚀 Игра начинается! {player_name} присоединился, и команда в полном составе!\n\n**{player_name}** — **{role}**\n\n{role_description}",
        "select_language": "🌐 **Выберите язык игры:**",
        "language_confirmation": "✅ **Выбран язык:** {language} {flag}",
        "name_question": "🗣 **Как вас зовут?**\n\nНапишите имя вашего персонажа (или своё настоящее имя):",
        "name_length_error": "Пожалуйста, напишите имя длиной от 1 до 50 символов:",
        "game_name_confirmation": "✅ Ваше игровое имя: {name}",
        "game_over_victory_title": "🏆 **ИГРА ЗАВЕРШЕНА — ПОБЕДА!**",
        "game_over_defeat_title": "💀 **ИГРА ЗАВЕРШЕНА — ПОРАЖЕНИЕ**",
        "game_over_continue": "🎮 **Что дальше?**\n\nВыберите игру, чтобы присоединиться, или начните новую:",
        "schedule_question": "⏰ **Расписание ходов**\n\nИгра будет автоматически генерировать новые ходы по расписанию. Выберите, как часто:\n\nНажмите одну из кнопок ниже или введите свой формат.\n\nПоддерживаемые форматы:\n• `6h` — каждые 6 часов\n• `8h` — каждые 8 часов\n• `12h` — каждые 12 часов\n• `24h` — каждые 24 часа\n• `30m` — каждые 30 минут (тестирование)\n• `08:00` — ежедневно в указанное время (UTC)",
        "schedule_set_confirm": "✅ **Расписание установлено:** {label}\n\nПервый ход будет сгенерирован автоматически.\n\nА теперь познакомимся!",
        "schedule_btn_6h": "6 часов",
        "schedule_btn_8h": "8 часов",
        "schedule_btn_12h": "12 часов",
        "schedule_btn_24h": "24 часа",
        "schedule_btn_custom": "✏️ Свой формат",
        "generating_images": "🎨 Генерирую иллюстрации для вашего приключения...\nЭто займёт около минуты. Пожалуйста, подождите.",
    },
    LANGUAGE_EN: {
        "welcome": None,  # Generated by LLM in game_server.py
        "welcome_back": "Welcome back, {role}!\n\n{role_description}\nTraits: {traits}\n\nUse /turn to view the current game turn.",
        "question_prefix": "Situation {id}:\n\n{text}",
        "onboarding_complete": "🎉 Welcome aboard!\n\nYour role: **{role}**\n\n{role_description}\n\n**Species:** {species}\n**Gender:** {gender}\n\n**Traits:**\n- {traits}",
        "game_already_started": "🚀 The game has already started! The crew is assembled. Use /turn for the current turn and /bridge to view the mission.",
        "game_waiting": "⏳ The game will start soon, we're waiting for more players.",
        "new_player_joined": "👋 A new crew member has joined us!\n\n**{player_name}** — **{role}**\n\n{role_description}",
        "select_game": "🎮 **Select a game to join or start a new one:**",
        "selected_game": "You selected 🎮 {game_name}",
        "new_game": "🆕 Start New Game",
        "invite_title": "🎯 **Invite friends!**",
        "invite_message": "Share this link with friends so they can join your game:\n{invite_url}",
        "invite_button": "🔗 Share Invite Link",
        "share_text": "Join the game",
        "invite_mission_caption": "I invite you to the game «{game_title}»!\n\n🚀 **Mission «{mission_name}»**\n\n{mission_description}\n\n{invite_url}",
        "invite_no_mission_caption": "I invite you to the game «{game_title}»!\n\n{invite_url}",
        "invite_forward": "👆 Forward the message above to a friend!\n\nOr send them this link:\n{invite_url}",
        "already_in_onboarding": "You are already in onboarding. Please answer the current question.",
        "onboarding_complete_restored": "🎉 Your onboarding is already complete! Creating your profile...",
        "stale_onboarding_session": "😕 Your onboarding session is stale. Press the button below to clear it and start fresh.",
        "clear_session_button": "🔄 Clear and Start Over",
        "game_starting_broadcast": "🚀 The game is starting! {player_name} has joined, and the crew is assembled!\n\n**{player_name}** — **{role}**\n\n{role_description}",
        "select_language": "🌐 **Choose game language:**",
        "language_confirmation": "✅ **Language selected:** {language} {flag}",
        "name_question": "🗣 **What is your name?**\n\nEnter your character name (or your real name):",
        "name_length_error": "Please enter a name between 1 and 50 characters:",
        "game_name_confirmation": "✅ Your game name: {name}",
        "game_over_victory_title": "🏆 **GAME OVER — VICTORY!**",
        "game_over_defeat_title": "💀 **GAME OVER — DEFEAT**",
        "game_over_continue": "🎮 **What next?**\n\nSelect a game to join or start a new one:",
        "schedule_question": "⏰ **Turn schedule**\n\nThe game will automatically generate new turns on a schedule. Choose how often:\n\nPress one of the buttons below or type your own format.\n\nSupported formats:\n• `6h` — every 6 hours\n• `8h` — every 8 hours\n• `12h` — every 12 hours\n• `24h` — every 24 hours\n• `30m` — every 30 minutes (testing)\n• `08:00` — daily at specified time (UTC)",
        "schedule_set_confirm": "✅ **Schedule set:** {label}\n\nThe first turn will be generated automatically.\n\nNow let's get to know you!",
        "schedule_btn_6h": "6 hours",
        "schedule_btn_8h": "8 hours",
        "schedule_btn_12h": "12 hours",
        "schedule_btn_24h": "24 hours",
        "schedule_btn_custom": "✏️ Custom format",
        "generating_images": "🎨 Generating illustrations for your adventure...\nThis should take about a minute. Please wait.",
    },
}

# Commands help
HELP = {
    LANGUAGE_RU: {
        "title": None,  # Game title fetched dynamically from API
        "regular_commands": "Команды:\n/start - Начать или продолжить игру\n/profile - Показать ваш профиль\n/turn - Текущий ход игры\n/team - Ваш экипаж\n/bridge - Картинка рубки и миссия\n/invite - Пригласить друга\n/reset - Сбросить участие и начать заново\n/help - Эта справка",
        "gm_commands": "Команды Game Master:\n/gm_start <id> - Запустить игру\n/gm_continue <id> - Сгенерировать следующий ход\n/gm_turn <id> - Перегенерировать текущий ход\n/gm_restart <id> - Перезапустить игру с 1 хода\n/gm_pause - Пауза/возобновление планировщика\n/gm_kick <id> <роль> [причина] - Изгнать игрока\n/gm_list - Список всех игр\n/gm_status <id> - Статус игры: игроки, NPC, выборы\n/gm_schedule <id> <формат> - Установить расписание игры\n/gm_lang <id> <ru|en> - Сменить язык и перегенерировать название игры",
        "how_to_play": "Как играть:\n1. Каждый ход генерируется новый сюжет\n2. Вы выбираете действия из предложенных вариантов\n3. Ваши решения влияют на развитие истории\n4. Вы можете общаться с Game Master в любое время\n\nНапишите сообщение для общения с Game Master.",
    },
    LANGUAGE_EN: {
        "title": None,  # Game title fetched dynamically from API
        "regular_commands": "Commands:\n/start - Start or continue the game\n/profile - Show your profile\n/turn - Current game turn\n/team - Your crew\n/bridge - Bridge image and mission\n/invite - Invite a friend\n/reset - Reset participation and start over\n/help - This help",
        "gm_commands": "Game Master Commands:\n/gm_start <id> - Start a game\n/gm_continue <id> - Generate the next turn\n/gm_turn <id> - Regenerate the current turn\n/gm_restart <id> - Restart the game from turn 1\n/gm_pause - Pause/resume the scheduler\n/gm_kick <id> <role> [reason] - Kick a player\n/gm_list - List all games\n/gm_status <id> - Game status: players, NPCs, choices\n/gm_schedule <id> <format> - Set per-game schedule\n/gm_lang <id> <ru|en> - Change language and regenerate game title",
        "how_to_play": "How to play:\n1. A new story is generated every turn\n2. You choose actions from the suggested options\n3. Your decisions affect the story development\n4. You can communicate with the Game Master at any time\n\nWrite a message to communicate with the Game Master.",
    },
}

# Profile messages
PROFILE = {
    LANGUAGE_RU: {
        "title": "👤 **Ваш профиль**",
        "role": "**Роль:** {role}",
        "species": "**Вид:** {species}",
        "gender": "**Пол:** {gender}",
        "description": "{role_description}",
        "traits": "**Характеристики:**\n- {traits}",
        "visualization": "**Визуализация:** {avatar}",
        "no_profile": "У вас ещё нет профиля. Пройдите онбординг с помощью /start",
        "hybrid_species": "Гибрид: {primary} + {secondary}",
        "hybrid_gender": "Гибрид: {primary} + {secondary}",
    },
    LANGUAGE_EN: {
        "title": "👤 **Your Profile**",
        "role": "**Role:** {role}",
        "species": "**Species:** {species}",
        "gender": "**Gender:** {gender}",
        "description": "{role_description}",
        "traits": "**Traits:**\n- {traits}",
        "visualization": "**Visualization:** {avatar}",
        "no_profile": "You don't have a profile yet. Complete onboarding with /start",
        "hybrid_species": "Hybrid: {primary} + {secondary}",
        "hybrid_gender": "Hybrid: {primary} + {secondary}",
    },
}

# Current turn messages
CURRENT_TURN = {
    LANGUAGE_RU: {
        "title": "🎯 **Ход {turn}**",
        "story": "*Общая вводная:*\n{story}",
        "crew_dialogues": "*Поведение экипажа:*",
        "actions": "*Ваши варианты действий:*\n{actions}",
        "select_action": "Выберите действие ниже:",
        "briefing_header": "{briefing}",
        "error": "Не удалось получить информацию о текущем ходе: {error}",
        "outcome_title": "🎬 **Итоги хода {turn}**",
        "global_intro_title": "🌌 **Ход {turn} — Общая вводная**",
        "game_over_victory_title": "🏆 **Игра завершена — Победа!**",
        "game_over_defeat_title": "💀 **Игра завершена — Поражение**",
        "game_over_reason_mission_complete": "Миссия выполнена успешно.",
        "game_over_reason_ship_destroyed": "Корабль уничтожен.",
        "game_over_reason_crew_wiped": "Весь экипаж погиб.",
        "game_over_reason_game_over": "Игра окончена.",
        "game_over_no_finale": "Игра завершена, но финальная история недоступна.",
    },
    LANGUAGE_EN: {
        "title": "🎯 **Turn {turn}**",
        "story": "*Global scenario:*\n{story}",
        "crew_dialogues": "*Crew behavior:*",
        "actions": "*Your action choices:*\n{actions}",
        "select_action": "Select an action below:",
        "briefing_header": "{briefing}",
        "error": "Could not get information about the current turn: {error}",
        "outcome_title": "🎬 **Turn {turn} Outcome**",
        "global_intro_title": "🌌 **Turn {turn} — Common Briefing**",
        "game_over_victory_title": "🏆 **Game Over — Victory!**",
        "game_over_defeat_title": "💀 **Game Over — Defeat**",
        "game_over_reason_mission_complete": "Mission completed successfully.",
        "game_over_reason_ship_destroyed": "Ship destroyed.",
        "game_over_reason_crew_wiped": "All crew lost.",
        "game_over_reason_game_over": "Game over.",
        "game_over_no_finale": "Game ended, but the finale is unavailable.",
    },
}

# Action selection
ACTIONS = {
    LANGUAGE_RU: {
        "recorded": "Ваш выбор записан!\n\nGame Master обработает ваше решение и обновит сюжет.\n\nВы можете продолжить общение с Game Master или подождать следующего дня.",
        "error": "Произошла ошибка при записи выбора: {error}",
        "action_caption": "🎬 Ваше действие в эпизоде сегодняшнего дня",
    },
    LANGUAGE_EN: {
        "recorded": "Your choice has been recorded!\n\nThe Game Master will process your decision and update the plot.\n\nYou can continue communicating with the Game Master or wait for the next turn.",
        "error": "An error occurred while recording the choice: {error}",
        "action_caption": "🎬 Your action in the current episode",
    },
}

# Message handling
MESSAGES = {
    LANGUAGE_RU: {
        "voice_received": "Спасибо за голосовое сообщение!\nGame Master получил ваше сообщение.\nПримечание: голосовые сообщения пока не поддерживают преобразование в текст.",
        "text_received": "Game Master получил ваше сообщение.\nОтвет будет сгенерирован в ближайшее время.",
        "error": "Произошла ошибка: {error}",
        "game_master_response": "Game Master получил ваше сообщение.",
    },
    LANGUAGE_EN: {
        "voice_received": "Thank you for the voice message!\nThe Game Master has received your message.\nNote: Voice messages do not support text-to-speech conversion yet.",
        "text_received": "The Game Master has received your message.\nThe response will be generated shortly.",
        "error": "An error occurred: {error}",
        "game_master_response": "Game Master received your message.",
    },
}

# Error messages
ERRORS = {
    LANGUAGE_RU: {
        "invalid_format": "Неверный формат ответа",
        "session_not_found": "Сессия не найдена. Пожалуйста, начните заново с /start",
        "onboarding_error": "Произошла ошибка при запуске: {error}",
        "stale_question": "Этот вопрос уже неактивен. Ответьте на текущий вопрос.",
    },
    LANGUAGE_EN: {
        "invalid_format": "Invalid answer format",
        "session_not_found": "Session not found. Please start again with /start",
        "onboarding_error": "An error occurred during startup: {error}",
        "stale_question": "This question is no longer active. Answer the current question.",
    },
}

# Loading / splash screen messages
IMAGES = {
    LANGUAGE_RU: {
        "loading_caption": "🚀 Инициализация системы... Загрузка звёздного компьютера.",
        "processing_caption": "✨ Ваши ответы обрабатываются. Личное дело шифрутеся звёздной пылью",
    },
    LANGUAGE_EN: {
        "loading_caption": "🚀 System initializing... Starship computer booting up.",
        "processing_caption": "✨ Your answer processing. Stellar cartography mapping your destiny",
    },
}

# Bridge image messages
BRIDGE = {
    LANGUAGE_RU: {
        "title": "🚀 **Мостик корабля**",
        "error": "Картинка рубки пока не сгенерирована. Дождитесь начала миссии.",
        "mission_header": "**Миссия:** {name}",
        "mission_desc": "{description}",
        "objectives_header": "**Цели миссии:**",
    },
    LANGUAGE_EN: {
        "title": "🚀 **Bridge**",
        "error": "Bridge image not yet generated. Wait for the mission to start.",
        "mission_header": "**Mission:** {name}",
        "mission_desc": "{description}",
        "objectives_header": "**Mission Objectives:**",
    },
}

# Spectator (dead player) messages
SPECTATOR = {
    LANGUAGE_RU: {
        "player_dead": "💀 **Вы погибли при исполнении!**\n\nВаш персонаж пал в бою. Вы остаётесь зрителем и можете наблюдать за развитием сюжета.\n\nЧтобы присоединиться к новой игре или вернуться в текущую в новой роли, нажмите /start",
        "still_watching": "👁 **Вы наблюдаете за развитием событий...**\n\nКак зритель, вы видите сюжет, но не можете влиять на него.\nНажмите /start чтобы присоединиться к новой игре или вернуться в новой роли.",
        "start_over_button": "🔄 Начать заново / Start Over",
    },
    LANGUAGE_EN: {
        "player_dead": "💀 **You died in the line of duty!**\n\nYour character fell in battle. You remain a spectator and can watch the story unfold.\n\nTo join a new game or return to the current one in a new role, press /start",
        "still_watching": "👁 **You are watching the story unfold...**\n\nAs a spectator, you see the plot but cannot influence it.\nPress /start to join a new game or return in a new role.",
        "start_over_button": "🔄 Start Over",
    },
}

# Team roster messages
TEAM = {
    LANGUAGE_RU: {
        "header": "👥 **Команда корабля**\n\n{count} членов экипажа",
        "roster": "**Состав команды:**\n{details}",
        "entry": "{name} — {role} | {species} | {gender}",
        "entry_dead": "💀 {name} — {role} | {species} | {gender}",
        "no_team": "🚫 Команда не найдена. Сначала присоединитесь к игре.",
        "api_error": "❌ Ошибка получения данных команды.",
    },
    LANGUAGE_EN: {
        "header": "👥 **Ship's Crew**\n\n{count} crew members",
        "roster": "**Crew Roster:**\n{details}",
        "entry": "{name} — {role} | {species} | {gender}",
        "entry_dead": "💀 {name} — {role} | {species} | {gender}",
        "no_team": "🚫 No crew found. Join a game first.",
        "api_error": "❌ Error fetching crew data.",
    },
}


def get_team(language: str = LANGUAGE_RU):
    """Get team roster messages for a specific language"""
    return TEAM.get(language, TEAM[LANGUAGE_RU])


# Notification messages sent to players (via push)
NOTIFICATIONS = {
    LANGUAGE_RU: {
        "game_restarted": ("⚠️ **Игра была перезапущена Game Master-ом!**\n\nВсе предыдущие ходы удалены. История начинается заново.\nВаш персонаж и роль сохранены.\n"),
    },
    LANGUAGE_EN: {
        "game_restarted": ("⚠️ **The game has been restarted by the Game Master!**\n\nAll previous turns have been deleted. The story begins anew.\nYour character and role are preserved.\n"),
    },
}


def get_notifications(language: str = LANGUAGE_RU):
    """Get notification messages for a specific language"""
    return NOTIFICATIONS.get(language, NOTIFICATIONS[LANGUAGE_RU])


# Menu labels
MENU = {
    LANGUAGE_RU: {
        "start": "/start",
        "profile": "/profile",
        "turn": "/turn",
        "team": "/team",
        "help": "/help",
        "invite": "/invite",
        "reset": "/reset",
    },
    LANGUAGE_EN: {
        "start": "/start",
        "profile": "/profile",
        "turn": "/turn",
        "team": "/team",
        "help": "/help",
        "invite": "/invite",
        "reset": "/reset",
    },
}

# /reset command — leave current game (replaced by NPC) and start over
RESET = {
    LANGUAGE_RU: {
        "confirm": (
            "⚠️ **Сброс участия в игре**\n\n"
            "Это действие необратимо. Вы покинете текущую игру — ваш персонаж будет "
            "заменён на NPC, а все ответы онбординга будут удалены. Затем вы сможете "
            "начать заново с выбора языка и вступления в новую игру.\n\n"
            "Продолжить?"
        ),
        "confirm_yes": "✅ Начать заново",
        "confirm_no": "❌ Отмена",
        "cancelled": "Сброс отменён, вы продолжаете в текущей игре.",
        "nothing_to_reset": "У вас нет активного профиля или онбординга — нечего сбрасывать. Используйте /start, чтобы начать.",
        "resetting": "⏳ Сбросываю ваше участие в игре...",
        "success": ("✅ **Сброс выполнен!**\n\nВаш персонаж заменён на NPC{npc_part}, профиль и онбординг удалены.\n\nДавайте начнём сначала 🌐"),
        "success_npc_part": ": {npc_name}",
        "error": "Не удалось выполнить сброс: {error}",
    },
    LANGUAGE_EN: {
        "confirm": (
            "⚠️ **Reset game participation**\n\n"
            "This is irreversible. You will leave your current game — your character "
            "will be replaced by an NPC, and all your onboarding answers will be "
            "deleted. You can then start over from language selection and join a new "
            "game.\n\n"
            "Continue?"
        ),
        "confirm_yes": "✅ Start over",
        "confirm_no": "❌ Cancel",
        "cancelled": "Reset cancelled — you remain in your current game.",
        "nothing_to_reset": "You have no active profile or onboarding to reset. Use /start to begin.",
        "resetting": "⏳ Resetting your game participation...",
        "success": ("✅ **Reset complete!**\n\nYour character was replaced by an NPC{npc_part}, your profile and onboarding have been deleted.\n\nLet's start over 🌐"),
        "success_npc_part": ": {npc_name}",
        "error": "Reset failed: {error}",
    },
}

# Game Master command responses
GM_COMMANDS = {
    LANGUAGE_RU: {
        "unauthorized": "⛔ У вас нет прав на использование этой команды.",
        "start_game_usage": "❌ Использование: /gm_start <game_id>\n\nПример: /gm_start abc123",
        "starting_game": "🚀 Запуск игры `{game_id}`...",
        "game_generation_started": "🚀 Запущена генерация игры `{game_id}`...\n⏳ Создаю NPC, миссию и бриффинги. Это может занять несколько минут.\n📬 Вы получите уведомление, когда игра будет готова.",
        "start_game_failed": "❌ Не удалось запустить игру: {error}",
        "continue_game_usage": "❌ Использование: /gm_continue <game_id>\n\nПример: /gm_continue abc123",
        "continuing_game": "🚀 Генерация следующего хода для игры `{game_id}`...",
        "turn_generation_started": "🚀 Запущена генерация хода для игры `{game_id}`...\n⏳ Это может занять несколько минут.\n📬 Вы получите уведомление, когда ход будет готов.",
        "continue_game_failed": "❌ Не удалось запустить генерацию хода: {error}",
        "game_continued": "✅ **Следующий ход сгенерирован!**\n\n🎯 Ход: {turn_num}\n👤 Игроков: {players}\n🤖 NPC: {npcs}\n🎭 Участников: {total}",
        "continue_game_error": "❌ Ошибка генерации хода: {error}",
        "regenerate_turn_usage": "❌ Использование: /gm_turn <game_id>\n\nПример: /gm_turn abc123",
        "regenerating_turn": "🔄 Перегенерация текущего хода для игры `{game_id}`...",
        "turn_regeneration_started": "🔄 Запущена перегенерация хода для игры `{game_id}`...\n⏳ Это может занять несколько минут.\n📬 Вы получите уведомление, когда ход будет готов.",
        "regenerate_turn_failed": "❌ Не удалось запустить перегенерацию хода: {error}",
        "turn_regenerated": "✅ **Текущий ход перегенерирован!**\n\n🎯 Ход: {turn_num}\n👤 Игроков: {players}\n🤖 NPC: {npcs}",
        "regenerate_turn_error": "❌ Ошибка перегенерации хода: {error}",
        "restart_game_usage": "❌ Использование: /gm_restart <game_id>\n\nПример: /gm_restart abc123",
        "restarting_game": "🔄 Перезапуск игры `{game_id}`...",
        "game_restarted": "✅ **Игра перезапущена!**\n\n🎮 Игра: `{game_id}`\n🗑 Удалено ходов: {deleted_turns}\n🗑 Удалено брифингов: {deleted_briefings}\n🗑 Удалено действий: {deleted_actions}\n🗑 Удалено сообщений: {deleted_messages}\n🗑 Удалена миссия: {deleted_mission}\n\n🎯 Ход: {turn_num}\n👤 Игроков: {player_count}\n🤖 NPC создано: {npc_count}\n🚀 Миссия сгенерирована",
        "restart_game_error": "❌ Ошибка перезапуска игры: {error}",
        "restart_cleanup_done": "✅ **Игра `{game_id}` сброшена!**\n\n🗑 Удалено ходов: {deleted_turns}\n🗑 Удалено брифингов: {deleted_briefings}\n🗑 Удалено действий: {deleted_actions}\n\n🚀 Запущена генерация новой игры...\n📬 Вы получите уведомление, когда игра будет готова.",
        "game_started": "✅ **Игра `{game_id}` запущена!**\n\n🎯 Ход: {turn_num}\n👤 Игроков: {player_count}\n🤖 NPC создано: {npc_count}\n🚀 Миссия сгенерирована\n🖼 Картинка рубки готова\n\nКоманда собрана, вводные разосланы!",
        "briefings_sent": "",
        "start_game_error": "❌ Ошибка запуска игры: {error}",
        "kick_usage": "❌ Использование: /gm_kick <game_id> <role_key> [причина]\n\nПример: /gm_kick abc123 chief_engineer Неактивен более 3 дней",
        "default_kick_reason": "Не указана",
        "kicking_player": "⏳ Изгнание игрока с ролью `{role_key}` из игры `{game_id}`...",
        "player_kicked": "✅ **Игрок изгнан!**\n\n🎮 Игра: `{game_id}`\n👤 Игрок: `{kicked_id}`\n🤖 Заменён NPC: {npc_name}\n📝 Причина: {reason}\n\nУведомление отправлено игроку.",
        "unknown_error": "Неизвестная ошибка",
        "no_api_response": "Нет ответа от API",
        "kick_error": "❌ Ошибка изгнания игрока: {error}",
        "ship_intact": "✅ Цел",
        "ship_destroyed": "☠ Уничтожен",
        "waiting_label": "Ожидание...",
        "no_data_label": "Нет данных",
        "no_games": "📋 **Список игр:**\n\nПока нет доступных игр.",
        "games_list_header": "📋 **Список игр:**",
        "games_list_entry": "{idx}. `{game_id}` — {title} (Ход: {turn}, {player_count} игр., {onboarding_count} онб., {status_icon} {status})",
        "default_game_title": "Без названия",
        "status_usage": "❌ Использование: /gm_status <game_id>\n\nПример: /gm_status abc123",
        "status_loading": "⏳ Получение статуса игры `{game_id}`...",
        "status_header": "📊 **Статус игры `{game_id}`**\n\n🎯 Ход: {turn}\n🚀 Статус: {status}\n🛸 Корабль: {ship}\n👤 Игроков: {player_count} (живых: {alive_count})\n🤖 NPC: {npc_count} (активных: {npc_alive_count})",
        "status_players_header": "\n\n**👤 Игроки:**",
        "status_player_entry": "{icon} `{player_id}` **{name}** — {role} | Выбор: {action}",
        "status_npcs_header": "\n\n**🤖 NPC:**",
        "status_npc_entry": "{icon} **{name}** — {role} | Выбор: {action}",
        "status_no_players": "\n\n_Нет игроков_",
        "status_no_npcs": "\n\n_Нет NPC_",
        "status_error": "❌ Ошибка получения статуса: {error}",
        "list_games_error": "❌ Ошибка получения списка игр: {error}",
        "game_ended_label": "🏁 Игра завершена",
        "ended_reason_mission_complete": "🏆 Миссия выполнена — победа!",
        "ended_reason_ship_destroyed": "💀 Корабль уничтожен",
        "ended_reason_crew_wiped": "☠ Весь экипаж погиб",
        "ended_reason_game_over": "Игра окончена",
        "status_ended_header": "🏁 **Игра `{game_id}` завершена**\n\n🎯 Финальный ход: {turn}\n⚰️ Причина: {reason}\n🛸 Корабль: {ship}\n👤 Игроков: {player_count} (в живых: {alive_count})\n🤖 NPC: {npc_count} (активных: {npc_alive_count})",
        "set_language_usage": "❌ Использование: /gm_lang <game_id> <ru|en>\n\nПример: /gm_lang abc123 en",
        "set_language_invalid": "❌ Язык должен быть `ru` или `en`.",
        "set_language_progress": "⏳ Меняю язык игры `{game_id}` на `{lang_code}`, генерирую название и миссию...",
        "set_language_success": "✅ **Язык игры `{game_id}` изменён на `{lang_code}`**\n\n🌐 Название игры: **{title}**",
        "set_language_error": "❌ Ошибка: {detail}",
        "next_turn_at": "Следующий ход: {time}",
        "next_turn_auto": "Следующий авто-ход: {time}",
        "next_turn_short": "след. {time}",
        "scheduler_paused": "⚠️ Планировщик на паузе",
        "scheduler_paused_label": "на паузе",
        "scheduler_unavailable": "Планировщик недоступен",
        "pause_usage": "❌ Использование: /gm_pause\nПереключает планировщик (пауза/возобновление).",
        "pause_toggled": "Планировщик: {state}",
        "pause_error": "❌ Ошибка переключения планировщика: {error}",
        "schedule_usage": "❌ Использование: /gm_schedule <game_id> <формат>\n\nФорматы: 6h (каждые N часов), 30m (каждые N минут), 08:00 (ежедневно в HH:MM)\n\nПример: /gm_schedule abc123 6h",
        "setting_schedule": "⏳ Устанавливаю расписание `{schedule}` для игры `{game_id}`...",
        "schedule_set": "✅ **Расписание для игры `{game_id}` установлено**\n\n📅 Расписание: {schedule_label}\n🕐 Следующий ход: {next_run}",
        "schedule_error": "❌ Ошибка: {error}",
        "schedule_label_daily": "ежедневно в {time}",
        "schedule_label_interval": "каждые {seconds}",
        "schedule_entry": "📅 Расписание: {schedule_label}\n🕐 Следующий ход: {next_run}",
    },
    LANGUAGE_EN: {
        "unauthorized": "⛔ You don't have permission to use this command.",
        "start_game_usage": "❌ Usage: /gm_start <game_id>\n\nExample: /gm_start abc123",
        "starting_game": "🚀 Starting game `{game_id}`...",
        "continue_game_usage": "❌ Usage: /gm_continue <game_id>\n\nExample: /gm_continue abc123",
        "continuing_game": "🚀 Generating next turn for game `{game_id}`...",
        "game_continued": "✅ **Next turn generated!**\n\n🎯 Turn: {turn_num}\n👤 Players: {players}\n🤖 NPCs: {npcs}\n🎭 Total: {total}",
        "continue_game_error": "❌ Error generating turn: {error}",
        "regenerate_turn_usage": "❌ Usage: /gm_turn <game_id>\n\nExample: /gm_turn abc123",
        "regenerating_turn": "🔄 Regenerating current turn for game `{game_id}`...",
        "turn_regenerated": "✅ **Current turn regenerated!**\n\n🎯 Turn: {turn_num}\n👤 Players: {players}\n🤖 NPCs: {npcs}",
        "regenerate_turn_error": "❌ Error regenerating turn: {error}",
        "restart_game_usage": "❌ Usage: /gm_restart <game_id>\n\nExample: /gm_restart abc123",
        "restarting_game": "🔄 Restarting game `{game_id}`...",
        "game_restarted": "✅ **Game restarted!**\n\n🎮 Game: `{game_id}`\n🗑 Turns deleted: {deleted_turns}\n🗑 Briefings deleted: {deleted_briefings}\n🗑 Actions deleted: {deleted_actions}\n🗑 Messages deleted: {deleted_messages}\n🗑 Mission deleted: {deleted_mission}\n\n🎯 Turn: {turn_num}\n👤 Players: {player_count}\n🤖 NPCs created: {npc_count}\n🚀 Mission generated",
        "restart_game_error": "❌ Error restarting game: {error}",
        "game_started": "✅ **Game `{game_id}` started!**\n\n🎯 Turn: {turn_num}\n👤 Players: {player_count}\n🤖 NPCs created: {npc_count}\n🚀 Mission generated\n🖼 Bridge image ready\n\nCrew assembled, briefings sent!",
        "briefings_sent": "",
        "start_game_error": "❌ Error starting game: {error}",
        "kick_usage": "❌ Usage: /gm_kick <game_id> <role_key> [reason]\n\nExample: /gm_kick abc123 chief_engineer Inactive for more than 3 days",
        "default_kick_reason": "Not specified",
        "kicking_player": "⏳ Kicking player with role `{role_key}` from game `{game_id}`...",
        "player_kicked": "✅ **Player kicked!**\n\n🎮 Game: `{game_id}`\n👤 Player: `{kicked_id}`\n🤖 Replaced by NPC: {npc_name}\n📝 Reason: {reason}\n\nNotification sent to player.",
        "unknown_error": "Unknown error",
        "no_api_response": "No API response",
        "kick_error": "❌ Error kicking player: {error}",
        "ship_intact": "✅ Intact",
        "ship_destroyed": "☠ Destroyed",
        "waiting_label": "Waiting...",
        "no_data_label": "No data",
        "no_games": "📋 **Game list:**\n\nNo games available yet.",
        "games_list_header": "📋 **Game list:**",
        "games_list_entry": "{idx}. `{game_id}` — {title} (Turn: {turn}, {player_count} pl., {onboarding_count} onb., {status_icon} {status})",
        "default_game_title": "Untitled",
        "status_usage": "❌ Usage: /gm_status <game_id>\n\nExample: /gm_status abc123",
        "status_loading": "⏳ Fetching game status for `{game_id}`...",
        "status_header": "📊 **Game `{game_id}` status**\n\n🎯 Turn: {turn}\n🚀 Status: {status}\n🛸 Ship: {ship}\n👤 Players: {player_count} (alive: {alive_count})\n🤖 NPCs: {npc_count} (active: {npc_alive_count})",
        "status_players_header": "\n\n**👤 Players:**",
        "status_player_entry": "{icon} `{player_id}` **{name}** — {role} | Choice: {action}",
        "status_npcs_header": "\n\n**🤖 NPCs:**",
        "status_npc_entry": "{icon} **{name}** — {role} | Choice: {action}",
        "status_no_players": "\n\n_No players_",
        "status_no_npcs": "\n\n_No NPCs_",
        "status_error": "❌ Error fetching game status: {error}",
        "list_games_error": "❌ Error fetching game list: {error}",
        "game_ended_label": "🏁 Game ended",
        "ended_reason_mission_complete": "🏆 Mission completed — victory!",
        "ended_reason_ship_destroyed": "💀 Ship destroyed",
        "ended_reason_crew_wiped": "☠ All crew lost",
        "ended_reason_game_over": "Game over",
        "status_ended_header": "🏁 **Game `{game_id}` ended**\n\n🎯 Final turn: {turn}\n⚰️ Reason: {reason}\n🛸 Ship: {ship}\n👤 Players: {player_count} (alive: {alive_count})\n🤖 NPCs: {npc_count} (active: {npc_alive_count})",
        "set_language_usage": "❌ Usage: /gm_lang <game_id> <ru|en>\n\nExample: /gm_lang abc123 en",
        "game_generation_started": "🚀 Game generation started for `{game_id}`...\n⏳ Creating NPCs, mission and briefings. This may take a few minutes.\n📬 You will be notified when the game is ready.",
        "start_game_failed": "❌ Failed to start game: {error}",
        "turn_generation_started": "🚀 Turn generation started for game `{game_id}`...\n⏳ This may take a few minutes.\n📬 You will be notified when the turn is ready.",
        "continue_game_failed": "❌ Failed to start turn generation: {error}",
        "turn_regeneration_started": "🔄 Turn regeneration started for game `{game_id}`...\n⏳ This may take a few minutes.\n📬 You will be notified when the turn is ready.",
        "regenerate_turn_failed": "❌ Failed to start turn regeneration: {error}",
        "restart_cleanup_done": "✅ **Game `{game_id}` reset!**\n\n🗑 Turns deleted: {deleted_turns}\n🗑 Briefings deleted: {deleted_briefings}\n🗑 Actions deleted: {deleted_actions}\n\n🚀 Starting new game generation...\n📬 You will be notified when the game is ready.",
        "set_language_invalid": "❌ Language must be `ru` or `en`.",
        "set_language_progress": "⏳ Changing game `{game_id}` language to `{lang_code}`, regenerating title and mission...",
        "set_language_success": "✅ **Game `{game_id}` language changed to `{lang_code}`**\n\n🌐 Game title: **{title}**",
        "set_language_error": "❌ Error: {detail}",
        "next_turn_at": "Next turn: {time}",
        "next_turn_auto": "Next auto-turn: {time}",
        "next_turn_short": "next {time}",
        "scheduler_paused": "⚠️ Scheduler paused",
        "scheduler_paused_label": "paused",
        "scheduler_unavailable": "Scheduler unavailable",
        "pause_usage": "❌ Usage: /gm_pause\nToggles the scheduler (pause/resume).",
        "pause_toggled": "Scheduler: {state}",
        "pause_error": "❌ Failed to toggle scheduler: {error}",
        "schedule_usage": "❌ Usage: /gm_schedule <game_id> <format>\n\nFormats: 6h (every N hours), 30m (every N minutes), 08:00 (daily at HH:MM)\n\nExample: /gm_schedule abc123 6h",
        "setting_schedule": "⏳ Setting schedule `{schedule}` for game `{game_id}`...",
        "schedule_set": "✅ **Schedule for game `{game_id}` set**\n\n📅 Schedule: {schedule_label}\n🕐 Next run: {next_run}",
        "schedule_error": "❌ Error: {error}",
        "schedule_label_daily": "daily at {time}",
        "schedule_label_interval": "every {seconds}",
        "schedule_entry": "📅 Schedule: {schedule_label}\n🕐 Next run: {next_run}",
    },
}


def get_onboarding(language: str = LANGUAGE_RU):
    """Get onboarding messages for a specific language"""
    return ONBOARDING.get(language, ONBOARDING[LANGUAGE_RU])


def get_help(language: str = LANGUAGE_RU):
    """Get help messages for a specific language"""
    return HELP.get(language, HELP[LANGUAGE_RU])


def get_profile(language: str = LANGUAGE_RU):
    """Get profile messages for a specific language"""
    return PROFILE.get(language, PROFILE[LANGUAGE_RU])


def get_current_turn(language: str = LANGUAGE_RU):
    """Get current turn messages for a specific language"""
    return CURRENT_TURN.get(language, CURRENT_TURN[LANGUAGE_RU])


def get_actions(language: str = LANGUAGE_RU):
    """Get action messages for a specific language"""
    return ACTIONS.get(language, ACTIONS[LANGUAGE_RU])


def get_messages(language: str = LANGUAGE_RU):
    """Get message handling strings for a specific language"""
    return MESSAGES.get(language, MESSAGES[LANGUAGE_RU])


def get_errors(language: str = LANGUAGE_RU):
    """Get error messages for a specific language"""
    return ERRORS.get(language, ERRORS[LANGUAGE_RU])


def get_menu(language: str = LANGUAGE_RU):
    """Get menu labels for a specific language"""
    return MENU.get(language, MENU[LANGUAGE_RU])


def get_reset(language: str = LANGUAGE_RU):
    """Get /reset command strings for a specific language"""
    return RESET.get(language, RESET[LANGUAGE_RU])


def get_images(language: str = LANGUAGE_RU):
    """Get loading/splash image messages for a specific language"""
    return IMAGES.get(language, IMAGES[LANGUAGE_RU])


def get_gm_commands(language: str = LANGUAGE_RU):
    """Get Game Master command response strings for a specific language"""
    return GM_COMMANDS.get(language, GM_COMMANDS[LANGUAGE_RU])


def get_bridge(language: str = LANGUAGE_RU):
    """Get bridge image messages for a specific language"""
    return BRIDGE.get(language, BRIDGE[LANGUAGE_RU])


# Push outcome messages
PUSH_OUTCOME = {
    LANGUAGE_RU: {
        "crew_behavior_header": "Поведение экипажа",
        "character_caption": "🎯 Ход {turn} — {role}",
        "ship_alive": "🚢 Корабль цел",
        "ship_destroyed": "💥 Корабль уничтожен!",
        "hull": "🛡 Корпус: {value}%",
        "shields": "🟡 Щиты: {value}%",
        "crew_alive": "👥 {alive} из {total} членов экипажа живы",
        "crew_alive_one": "👥 {alive} из {total} член экипажа жив",
        "death_notices_header": "☠ Потери экипажа:",
        "mission_progress_header": "🏆 Прогресс миссии:",
        "mission_progress_item": "  {direction}{points} этап {stage}",
        "systems_offline": "🚧 Системы отключены: {list}",
        "injured_header": "🤕 Раненые:",
        "severity_critical": "🔴 критическое",
        "severity_moderate": "🟡 среднее",
        "severity_minor": "🟢 лёгкое",
        "personal_outcomes_header": "🎬 Последствия хода:",
        "turn_prefix": "Ход {turn}",
    },
    LANGUAGE_EN: {
        "crew_behavior_header": "Crew behavior",
        "character_caption": "🎯 Turn {turn} — {role}",
        "ship_alive": "🚢 Ship is intact",
        "ship_destroyed": "💥 Ship destroyed!",
        "hull": "🛡 Hull: {value}%",
        "shields": "🟡 Shields: {value}%",
        "crew_alive": "👥 {alive} / {total} crew alive",
        "crew_alive_one": "👥 {alive} / {total} crew alive",
        "death_notices_header": "☠ Crew losses:",
        "mission_progress_header": "🏆 Mission progress:",
        "mission_progress_item": "  {direction}{points} stage {stage}",
        "systems_offline": "🚧 Systems offline: {list}",
        "injured_header": "🤕 Injured:",
        "severity_critical": "critical",
        "severity_moderate": "moderate",
        "severity_minor": "minor",
        "personal_outcomes_header": "🎬 Turn consequences:",
        "turn_prefix": "Turn {turn}",
    },
}


def get_push_outcome(language: str = LANGUAGE_RU):
    """Get push outcome messages for a specific language"""
    return PUSH_OUTCOME.get(language, PUSH_OUTCOME[LANGUAGE_RU])


def get_spectator(language: str = LANGUAGE_RU):
    """Get spectator/dead player messages for a specific language"""
    return SPECTATOR.get(language, SPECTATOR[LANGUAGE_RU])


def get_language_flag(lang_code: str) -> str:
    """Get the flag emoji for a language code (ru/en)."""
    return LANGUAGE_FLAGS.get(lang_code, "🌐")


def get_language_name(lang_code: str, display_language: str = LANGUAGE_RU) -> str:
    """Get the display name of a language in a given display language.

    Example: get_language_name("en", "ru") -> "English"
             get_language_name("ru", "en") -> "Russian"
    """
    names_map = LANGUAGE_NAMES.get(display_language, LANGUAGE_NAMES[LANGUAGE_RU])
    return names_map.get(lang_code, lang_code)
