FROM astral/uv:python3.14-bookworm-slim

RUN apt update && apt install -y curl
WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN uv pip install --no-cache --system --break-system-packages -r requirements.txt

# Copy application
COPY . .

# Run with uvicorn
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]