FROM astral/uv:python3.14-bookworm-slim

RUN mkdir -p /app
WORKDIR /app

RUN uv venv
RUN mkdir -p /app/data/custom_workflows /app/data/custom_starters
RUN uv pip install pixelle

EXPOSE 9004
CMD [ "/app/.venv/bin/pixelle","start" ]