FROM python:3.12-slim

RUN mkdir -p /app
WORKDIR /app

RUN uv venv
RUN uv install pixelle@latest
RUN mkdir -p /app/data/custom_workflows /app/data/custom_starters

EXPOSE 9004
CMD [ "/app/.venv/bin/pixelle","start" ]